### ISSUE TITLE
Cannot find SHOW MORE element on www.youtube.com

### ISSUE THREAD

**Issue by marvelfrozen** [manikanta-dornala/lyrics_for_music#1]
The addon failed to locate the "SHOW MORE" button, it seems.
Weird because on the page source, the locator should direct to the element correctly.

This on FF77.0b4 (64-bit)

![image](https://user-images.githubusercontent.com/29943195/82110483-13eed180-9769-11ea-908f-be087921aab6.png)

![image](https://user-images.githubusercontent.com/29943195/82110433-c4100a80-9768-11ea-8a6e-8d1898e9e208.png)

![image](https://user-images.githubusercontent.com/29943195/82110420-a6db3c00-9768-11ea-802f-a37661ae6873.png)

**Comment by marvelfrozen** [comment]
Also, on some related note, the script keep trying to find the element when failed, hangs the browser couple of times, might it be better to limit the retries? or set a button to retry manually?

**Comment by marvelfrozen** [comment]
Okay, I found the cause, there is another element with id = "more" before the one the script looking for.
So the script cannot find the correct one.

I checked the commit and it seems the latest commit with comment "fixing youtube bug" is the cause for this issue.

**Comment by manikanta-dornala** [comment]
A fix has been made for this to improve performance and reliability. Basically the video description parser was trying to click the show more button to expand the description to scrape the song details. There happens to be another element that matched the query selector. 
I pushed an update with the fix that picks the element in a more economical and certain way.
